### PR TITLE
Added ore dictionary support in JEI for Inscriber top slot and bottom slot

### LINKED ISSUE #404: [Requst]Use Ore dictionary to merge Inscriber's recipes in JEI
**Describe the feature**
When viewing Inscriber recipes, reduce the recipe list for Magnet Card to one. Supported lapis block and redstone block variants are constantly changing in this recipe

**Reasons why it should be considered**
The current magnet card recipe adds all variations, which results in a large number of meaningless recipes in the list, and players cannot find the recipes they need.

**Additional Context**

### PR DESCRIPTION
**Pull request by zeng-github01**
resolve #404 

This PR is assisted by BingAI

### CODE REVIEW

**Comment by zeng-github01** [comment]
What do you think of this PR? It can solve the problem of Inscriber having 150 pages of recipes

**Comment by NotMyWing** [comment]
I'm still looking into it, sorry. I have a huge backlog of issues and barely any time, but will get to it.

**Comment by zeng-github01** [comment]
> I'm still looking into it, sorry. I have a huge backlog of issues and barely any time, but will get to it.

Thanks a lot

**Review by NotMyWing — APPROVED** [review]

**Comment by brachy84** [comment]
me when changing api methods so groovyscript breaks

**Pull request merged**
