### PR TITLE
Backport lock crafting function for ME Interface

### LINKED ISSUE #394: [Request]Backport from future AE2
**Describe the feature**
In AE2 1.19, there is a new redstone control that is unlocked ME interface when pattern output is received. Using this function, you can achieve: when one raw material gets the product, then the next one is output.

**Reasons why it should be considered**

**Additional Context**

### PR DESCRIPTION
**Pull request by zeng-github01**
The purpose of this PR is to backport the Lock Crafting function and reserve interface functions for AE2FC to support this function.

resolve #394 

Related PR:
AE2-UEL/AE2FluidCraft-Rework#151

### CODE REVIEW

**Comment by zeng-github01** [comment]
@NotMyWing Could you help review it?

**Comment by NotMyWing** [comment]
Looks good to me in-game overall, I'll be testing this more thoroughly later on before merging.

**Comment by zeng-github01** [comment]
> Looks good to me in-game overall, I'll be testing this more thoroughly later on before merging.

I have used it in my own save for a long time. There are no errors so far. Looking forward to your test results. In addition, this PR and the PR for interface terminal improvement also modify status.png, which is the icon library file of AE2. Before merging, you need to merge the changes of these two PRs

**Comment by zeng-github01** [comment]
@NotMyWing There is also an issue that this PR does not backport the lock reason displayed on the GUI. There is not enough space and a suitable UI component.

**Review by NotMyWing — APPROVED** [review]

**Review by NotMyWing — APPROVED** [review]

**Comment by NotMyWing** [comment]
Merged via https://github.com/AE2-UEL/Applied-Energistics-2/commit/a13f9955f29e3fdcc2a1d9e1ddc8ea0159654a42.

**Pull request closed without merging**
