### PR TITLE
Fix ME Identity Annihilation Plane & ME Annihilation Plane Support Enchantment

### PR DESCRIPTION
**Pull request by zeng-github01**
屏幕截图 2024-11-15 234010

屏幕截图 2024-11-15 234042

Support Identity Annihilation Plane conversion. Behavior is consistent with the original AE2

### CODE REVIEW

**Comment by Rongmario** [comment]
Shake my head https://www.curseforge.com/minecraft/mc-mods/enhanced-annihilation-planes

**Comment by zeng-github01** [comment]
> Shake my head https://www.curseforge.com/minecraft/mc-mods/enhanced-annihilation-planes

Unfortunately, it looks like this repository will no longer be maintained.

**Comment by Rongmario** [comment]
The author is still definitely around, I don't see any issues or PRs over there.

**Comment by zeng-github01** [comment]
@Rongmario By the way, there are still some bugs in this PR. I am trying to fix it.

The enchantment of this part will disappear after re-entering the save file. However, the enchantment is actually work. You can also get the item with the corresponding enchantment after dismantling it.

**Comment by zeng-github01** [comment]
@Rongmario I have done my best to backport

It’s almost the same as the future AE, please review?

**Comment by Rongmario** [comment]
I don't work or have permissions on AE2's repo, I was mentioning that there already exists a mod that brings the good to annihilation planes without you having to work this hard...

**Comment by zeng-github01** [comment]
@Rongmario All done, lol

**Review by NotMyWing — APPROVED** [review]

**Pull request merged**
